services:
  # Web Service - Node.js Backend + Serve React Frontend
  - type: web
    name: educational-pdf-ai-app
    env: node
    repo: https://github.com/saanuj07/educational-pdf-ai-app.git
    branch: main
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: cd server && npm start
    plan: free
    region: oregon
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: WATSONX_API_KEY
        sync: false
      - key: WATSONX_URL
        value: https://eu-de.ml.cloud.ibm.com
      - key: WATSON_MODEL_ID
        value: ibm/granite-13b-instruct-v2
      - key: SPACE_ID
        sync: false
      - key: NLU_API_KEY
        sync: false
      - key: NLU_URL
        value: https://api.au-syd.natural-language-understanding.watson.cloud.ibm.com/instances/8a608f1f-b862-4373-b686-0f8b0d6fe35d
      - key: TTS_API_KEY
        sync: false
      - key: TTS_URL
        value: https://api.au-syd.text-to-speech.watson.cloud.ibm.com/instances/89d34c96-dfc3-4188-b965-07d598488a95
      - key: STT_API_KEY
        sync: false
      - key: STT_URL
        value: https://api.au-syd.speech-to-text.watson.cloud.ibm.com/instances/a4fae28a-5eb0-49e5-96fc-38f1a9776253
